### ISSUE TITLE
7tag installation not working

### ISSUE THREAD

**Issue by fabricehong** [seventag/seventag#170]
On the latest distribution release (version 1.0.1), after sucessfully installing 7tag (var/cache, database, drivers) and creating the admin, it redirect on the root which points to no file (no index.php present). I run the file app_dev.php and I get the following error message :

"ClassNotFoundException in AppKernel.php line 62: 
Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle". 
Did you forget a "use" statement for another namespace?"

Making a docker container for 7tag would be great to quickly try out the app without running into installation problems

**Comment by kallosz** [comment]
@fabricehong `app_dev.php` isn't available in default package. First you need to run `composer install` to download dev packages required for developer env.

We already have docker and [heroku](https://www.heroku.com) in our plans. I hope that will be available soon.

**Comment by fabricehong** [comment]
Hello!

the install guide doesn't talk about any composer command (https://7tag.org/docs/installation/). I'm just interested in trying out 7tag. I'm not a php developer.. 

I ran app_dev.php because app.php doesn't show any visible errors but stays blank.

**Comment by ArekZc** [comment]
@fabricehong Without composer app_dev.php can't be run, because to run it need some vendor dependencies, if you want to display errors you need to display log file.
``` bash
$ tail -f var/logs/prod.log
```
In installation manual we try to show how to install production environment

**Comment by kallosz** [comment]
@fabricehong whether the problem still occurs?

**Comment by integrated-analytics** [comment]
Hi,
we encountered the same problem: installation successful ("7tag Congigured") hittinng start results in a web directory listing. Following your hint above. we found following error message:

> [2015-12-11 15:43:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from  "http://111.111.111.206/")" at /var/www/seventag/var/cache/prod/classes.php line 2494 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(co
> de: 0): No route found for \"GET /\" (from \"http://111.111.111.206/\") at /var/www/seventag/var/cache/prod/classes.php:2494, Symfony\\Component\\Routing\\Exception\\R
esourceNotFoundException(code: 0):  at /var/www/seventag/var/cache/prod/appProdUrlMatcher.php:609)"} []
> [2015-12-11 15:43:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://111.111.111.206/")" at /var/www/seventag/var/cache/prod/classes.php line 2494 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(co
> de: 0): No route found for \"GET /\" (from \"http://111.111.111.111.206/\") at /var/www/seventag/var/cache/prod/classes.php:2494, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/seventag/var/cache/prod/appProdUrlMatcher.php:609)"} []

(IP Address changed).

Any idea? 

Best regards,

Werner

**Comment by pszostak** [comment]
Hey,
can you send vhost settings?

ClearcodeTechnology with Passion
Piotr SzostakProject Manager
www.clearcode.cc

2015-12-11 15:54 GMT+01:00 Integrated Analytics <notifications@github.com>:

**Comment by integrated-analytics** [comment]
Hi  Piotor,

sure!

<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/seventag/web/

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

Thanks for your help!

Werner

Von: pszostak [mailto:notifications@github.com]
Gesendet: Freitag, 11. Dezember 2015 15:58
An: seventag/seventag
Cc: Werner Emde
Betreff: Re: [seventag] 7tag installation not working (#170)

Hey,
can you send vhost settings?

ClearcodeTechnology with Passion
Piotr SzostakProject Manager
www.clearcode.cc<http://www.clearcode.cc>

2015-12-11 15:54 GMT+01:00 Integrated Analytics <notifications@github.com<mailto:notifications@github.com>>:

**Comment by integrated-analytics** [comment]
Hi,

is there anybody out there (not from Clearcode), who could install seventag without any problem?

Best regards,

Werner

**Comment by lyzkov** [comment]
Hello,
Please try to add `AllowOverride` and `Require` options to vhost config as follows:
```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot "/var/www/seventag/web/"
    <Directory "/var/www/seventag/web/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
