### ISSUE TITLE
display containers still in draft mode?

### ISSUE THREAD

**Issue by cdwiegand** [seventag/seventag#366]
Would it be difficult to add a column, maybe with icons, showing the published / draft status of containers? I'm finding some of my users forget to publish the container and so it doesn't work and they think it's WordPress, or the hosting provider, or even just mangled javascript copy/paste messing up the quotes, when it's really just the tags aren't published yet.

**Comment by pszostak** [comment]
It will be added in a future, but currently I'm not able to point release version.

**Comment by pszostak** [comment]
It's already released in v1.4.0
