### ISSUE TITLE
1.1 updater code requires memory_limit to not be set

### ISSUE THREAD

**Issue by cdwiegand** [seventag/seventag#384]
Tried upgrading from 1.1 to 1.2 online, and got an error that 512 MB memory_limit was too small. After digging through code, found that it wants it to be -1, which we don't normally allow in our environments. Also looks like timeout needs to be -1, and /tmp must be writable - instead you should consider using php's own temp dir functions (we set them, but we don't use a global /tmp, instead each site/user gets their own for security purposes).

**Comment by pszostak** [comment]
We are improving app updater, and it will be improved too. It will be fixed in v1.3.4.
