### ISSUE TITLE
updater.php assumes sys_get_temp_dir has DIRECTORY_SEPARATOR

### ISSUE THREAD

**Issue by cdwiegand** [seventag/seventag#389]
I found another issue with the 1.1 (and still present in 1.2!) updater - seventag/web/update.php assumes sys_get_temp_dir() ends with DIRECTORY_SEPARATOR. I had to manually add it to let the update run. I would strongly encourage putting that value in a variable and testing for DIRECTORY_SEPARATOR. Hosts using locked-down php.ini values may not append the trailing separator, and php does not require or append it itself.

// original code: 
sys_get_temp_dir() . uniqid('7tag_updater', true) . DIRECTORY_SEPARATOR . 'seventag'

// works: 
sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('7tag_updater', true) . DIRECTORY_SEPARATOR . 'seventag'

**Comment by kallosz** [comment]
Should be fixed in another release.
