### ISSUE TITLE
Rewrite rules in "/web/.htaccess" for static content

### ISSUE THREAD

**Issue by bensbox** [seventag/seventag#417]
After a fresh install and the redirection to the admin-panel, the browser is not able to load any static content which are in the "/web/admin-panel/app" folder.

I guess the rewrite rules from "/app/vendor.css" to "/admin-panel/app/vendor.css" are not correct.

![7tag-rewrite](https://cloud.githubusercontent.com/assets/2283498/12951237/a19b4c44-d011-11e5-9f1d-be3fcab16b40.png)

**Comment by pszostak** [comment]
Which 7tag version did you install? Can you share your vhost Apache config?
Please also check 7tag requirements: https://7tag.org/docs/software-requirements/
We added example Apache config.

**Comment by bensbox** [comment]
Ok, the config was not clear. A "Options All" fixed it, but i recommend against the "All" settings in "AllowOverride" or "Options". You should define, which ones are necessary.

**Comment by muechert** [comment]
I have the same issue described by bensbox but I am not able to fix it.
In Firebog you see the 404 error and in Firefox itself you can see only a HTML "Toogle navigation" button and a broken image. That's it :(

The Apache Server Version is 2.2 and I tried exeactly the Apache config mentioned under https://7tag.org/docs/software-requirements/
Does anybody have the same problem?

**Comment by pszostak** [comment]
muechert, can you share your vhost Apache config?

**Comment by bensbox** [comment]
@muechert : My config is:


ServerName 7tag.dev
ServerAlias www.7tag.dev

```
ServerAdmin webmaster@localhost
DocumentRoot /data/www/7tag/htdocs/web

<Directory /data/www/7tag/htdocs/web/>
        Options All
        AllowOverride All
        Require all granted
</Directory>
```

The fun part is, that i just tried a fresh install of 7tag 1.3 in the same folder with the same vhost settings (which was fine the version before) and now i am not able to do anything again.

Firebug tells me for instance, that accessing "http://7tag.dev/api/translations/en.json" or "http://7tag.dev/api/users/me" is "401 Unauthorized" and returns the message:
> {"error":"invalid_grant","error_description":"The access token provided is invalid."}

Calling "en.json" directly is not a problem. The result is, that i get a blank page, with the 7tag logo and a loading image.

**Comment by pszostak** [comment]
bensbox, you have wrong DocumentRoot and directory. 
Recommended: 
/path/to/your/seventag/web

Please also set credentials for these folders by using chmod -R 777
– app/cache
– app/logs
– var/cache
– var/logs
– web/containers.

**Comment by bensbox** [comment]
No, the directory is correct. "/data/www/7tag/htdocs" is my "/path/to/your/seventag".
It now works after changing the permissions to the listed folders above.

I suggest to add more setup checks in the installer (Allowoverride, Options, Permissions, Rewrite enabled etc).
Btw - the folders above are were not listed in your installation guide couple of hours ago, which is the reason it did not work for me. I was looking them up to make sure i didn't miss anything and now the list changed.

**Comment by pszostak** [comment]
Thank you for feedback. We are updating our manual today and those folders info was updated too (added info about two additional folders). 
We also updated manual with new features released in 1.3.0.

Enjoy 7tag.

**Comment by muechert** [comment]
@pszostak: 
I tried ths http.conf:

`<VirtualHost *:80>
DocumentRoot /home/www/seventag/web
ServerName my-domain.com
ServerAlias my-domain.com
DirectoryIndex index.php
  
<Directory /home/www/seventag/web>
      AllowOverride All
      Order Allow,Deny
      Allow from all
 </Directory>
</VirtualHost>`

I created before via the administration panel of my web provider a subdomain called 7tag.my-domain.com and directed these domain to /seventag/web.
In fact, do I need the VirtualHost entries?
Sorry, I am not very familar with http.conf entries but runnig the setup was not an issue. Only the access later to the main user interface does not work.

**Comment by muechert** [comment]
Does anyone have an idea?

**Comment by zientalak** [comment]
@muechert You need VirtualHost entries too, e.q.:

```
<VirtualHost *:80>
  DocumentRoot "/path/to/your/seventag/web"
  ServerName yourseventag.com
  ServerAlias yourseventag.com
  DirectoryIndex index.php
  
  <Directory "/path/to/your/seventag/web">
      AllowOverride All
      Order Allow,Deny
      Allow from all
  </Directory>

</VirtualHost>
```

**Comment by muechert** [comment]
Dear zientalak,

thanks for your answer but also with exactly these settings the same issue appears.
Do you have any other ideas?

**Comment by zientalak** [comment]
@muechert

Can you show us Apache error log content from /var/log/apache2/error_log?

**Comment by muechert** [comment]
Dear zientalak,

thank you very much for your answer!
There are some errors regarding Seventag in the error_log.
You can find a snippet below:

[Tue Mar 15 18:26:14 2016] [notice] Apache/2.2.22 (Debian) DAV/2 SVN/1.6.17 PHP/5.5.33 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:18 2016] [error] [client 213.196.217.203] File does not exist: /home/www/seventag/web/admin-panel/redirect:, referer: http://7tag.example.com/
[Tue Mar 15 18:26:19 2016] [error] [client 213.196.217.203] no acceptable variant: /home/www/seventag/web/app, referer: http://7tag.example.com/
[Tue Mar 15 18:26:19 2016] [error] [client 213.196.217.203] no acceptable variant: /home/www/seventag/web/app, referer: http://7tag.example.com/
[Tue Mar 15 18:26:19 2016] [error] [client 213.196.217.203] no acceptable variant: /home/www/seventag/web/app, referer: http://7tag.example.com/
[Tue Mar 15 18:26:19 2016] [error] [client 213.196.217.203] no acceptable variant: /home/www/seventag/web/app, referer: http://7tag.example.com/
[Tue Mar 15 18:26:20 2016] [error] [client 213.196.217.203] no acceptable variant: /home/www/seventag/web/app, referer: http://7tag.example.com/
[Tue Mar 15 18:26:20 2016] [error] [client 213.196.217.203] no acceptable variant: /home/www/seventag/web/app, referer: http://7tag.example.com/
