### ISSUE TITLE
7Tag Calling IP Address Instead of seventag_domain Value

### ISSUE THREAD

**Issue by damonhenry** [seventag/seventag#421]
We're using 7Tag Version 1.0.

7Tag makes the call below to the hosting servers IP address when deployed. I replaced the seventag_domain value IP address with the server's domain name but still not luck.

http://XX.XXX.XXX.XX/containers/tagtree/58.jsonp?callback=SevenTag_TagTreeCallback_0

**Comment by pszostak** [comment]
Hello, you need to clean App cache and Var cache (just delete all the files from those folders). 

I also recommend to instal the new version of 7tag. In next few days we will release v.1.3.
Check 7tag roadmap: https://7tag.org/roadmap/
