### ISSUE TITLE
installer returns error 500 after supplying username and passwords

### ISSUE THREAD

**Issue by RMastop** [seventag/seventag#429]
After supplying username and passwords in admin create, the system returns a 500 error.The URL that is shown in the navigationbar is:
/install.php/admin/create 

No detailed data available in error.log

version 1.3.0

**Comment by pszostak** [comment]
Please with updating to 1.3.0. It's not an official version yet. It will be released tomorrow.

**Comment by RMastop** [comment]
Using the latest version (v1.3.0, downloaded today) shows me the same result.
Is there a way to log the resulting error, to see what's wrong?

**Comment by pszostak** [comment]
I'm not sure, where the problem is, so we need to investigate.

1. Set credentials for these folders by using chmod -R 777
– app/cache
– app/logs
– var/cache
– var/logs
– web/containers.

2. clean cache manually: rm -rf var/cache/*

If it won't help we will try to look for another solution.

**Comment by RMastop** [comment]
in my case It was a server config error

I use Ubuntu 14.04 LTS X64
after installing the following items, I was able to setup the new environment.
apache2-mpm-prefork libapache2-mod-php5

**Comment by pszostak** [comment]
Thank you for your feedback. That's great it works now.

Enjoy 7tag
