### ISSUE TITLE
Mixed content while platform checks for version (in V 1.3.1)

### ISSUE THREAD

**Issue by RMastop** [seventag/seventag#444]
Hi,

I noticed the following call from my browser:
http://download.7tag.org/version.json?domain=<URL>&version=<RUNNINGVERSION>

Since I'm using an HTTPS connection I would expect it to use an HTTPS connection as well

It was called by:
vendor.js:2 

The error is:
Mixed Content: The page at 'https://<URL>/#/containers' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://download.7tag.org/version.json?domain=<URL>&version=<RUNNINGVERSION>'. This request has been blocked; the content must be served over HTTPS.

Running version: 1.3.1

**Comment by pszostak** [comment]
Hi, thank you for your feedback. We will fix it till Tuesday (2016-02-23). 
We will release v1.3.2 with few other fixes.

**Comment by pszostak** [comment]
Hello, we haven't finished working on it yet. It wasn't possible to fix the issue in v1.3.2. 
We are planning to fix it in v1.3.3.

**Comment by RMastop** [comment]
after updating to version 1.3.3 the issue is resolved.
