### ISSUE TITLE
cmd/ctrl + click is not working

### ISSUE THREAD

**Issue by paolooo** [seventag/seventag#449]
`Cmd / Ctrl + Click` on anchor tag should open a new window. What happen now is, it doesn't open a new window but instead it navigates on the same window.

**Comment by paolooo** [comment]
I've create a PR for this. See pull request #450

**Comment by pszostak** [comment]
Thanks for contributing to our product.
However, since we do not have contribution guidelines & terms, we are not able to merge it. 

We will provide your changes internally in v 1.3.3, which is currently under development.

Thank you.

**Comment by marnits** [comment]
This issue has been fixed in this PR:
https://github.com/seventag/seventag/pull/478

Will be released in version 1.4
