### ISSUE TITLE
what does the noscript.html iframe do?

### ISSUE THREAD

**Issue by lindsaymacvean** [seventag/seventag#483]
I am using drupal and it is optimal for me to enter just the javascript portion of the container code and leave off the iframe //yourseventag.com/containers/1/noscript.html

It just appears to be a json file, I am not sure what it is supposed to do?

**Comment by marnits** [comment]
7tag provides support for `noscript` tags, which are frequently used as a fallback in many popular analytic tools, e.g. Piwik, for supporting user tracking when a visitor turns off their Javascript.

What we do is simply store content from all `noscript` tags from your container (from Tag Templates and Custom HTML Tags) and put them into `noscript.html` tags one after another. If a visitor turns off Javascript support in their browser, 7tag loads `noscript.html`, which will render all `img` and/or `iframe` tags from `noscript` contents.
