### ISSUE TITLE
where should I see triggered tags in my piwik?

### ISSUE THREAD

**Issue by lindsaymacvean** [seventag/seventag#484]
I tried clicking on Actions -> Events 
and it displayed this error
Error: Action 'menuGetPageUrls' not found in the module 'Events'

Is this an issue I need to sort out with piwik or is it being caused by seventag?

**Comment by lindsaymacvean** [comment]
I think I might have fixed it by deactivating and reactivating various plugins in piwik, but now the action->events page loads it doesnt show any data, not sure if I am missing some other connection to feed data to piwik via the seventag script?

**Comment by pszostak** [comment]
Hello lindsaymacvean,
can you check 'Piwik site url' field in your tag?

The URL needs to start with http:// or https:// protocol definition. You can also use protocol-relative statement if you do not want to specify protocol.

It should solve your problem.
