### ISSUE TITLE
opt-out code in privacy tab shows 'http://' in URL instead of '//'

### ISSUE THREAD

**Issue by RMastop** [seventag/seventag#496]
opt-out code in privacy tab shows 'http://' in URL instead of '//'

`<!-- Start 7Tag privacy opt-out code --><script type="text/javascript" src="http://##SEVENTAGSERVERURL##/containers/1/privacy-script.js"></script><div id="_stg_opt_out_iframe_content" style="display: none;"><p>You can choose to opt out of being tracked by all marketing and advertising tools installed on this website.<br>To make that choice, please click below to receive an opt-out cookie.</p><input id="_stg_optout_checkbox" onclick="window.parent.storeUserOptOutPreferences();" type="checkbox"><label id="_stg_optout_checkbox_label" for="_stg_optout_checkbox"></label></div><iframe id="_stg_opt_out_iframe" style="border:none;" width="100%" height="105px" src="about:blank" onload="loadOptOut();"></iframe><!-- End 7Tag privacy opt-out code -->`

I would expect the following (like the general container code):

`<!-- Start 7Tag privacy opt-out code --><script type="text/javascript" src="//##SEVENTAGSERVERURL##/containers/1/privacy-script.js"></script><div id="_stg_opt_out_iframe_content" style="display: none;"><p>You can choose to opt out of being tracked by all marketing and advertising tools installed on this website.<br>To make that choice, please click below to receive an opt-out cookie.</p><input id="_stg_optout_checkbox" onclick="window.parent.storeUserOptOutPreferences();" type="checkbox"><label id="_stg_optout_checkbox_label" for="_stg_optout_checkbox"></label></div><iframe id="_stg_opt_out_iframe" style="border:none;" width="100%" height="105px" src="about:blank" onload="loadOptOut();"></iframe><!-- End 7Tag privacy opt-out code -->`

**Comment by pszostak** [comment]
Thank you for pointing this issue. We will improve it in v1.5.0.

**Comment by marnits** [comment]
PR for this issue
https://github.com/seventag/seventag/pull/497
