### ISSUE TITLE
7Tag not working after installation

### ISSUE THREAD

**Issue by suruchi-shah** [seventag/seventag#503]
At the last step of a successful installation, the CONTINUE button redirects to the root but it doesn't point anywhere. I am running it locally, and this is the error it shows:

![image](https://cloud.githubusercontent.com/assets/18153325/14187923/3e8d68a8-f73a-11e5-959e-275722aada29.png)

![image](https://cloud.githubusercontent.com/assets/18153325/14187936/4de4006e-f73a-11e5-93ef-9027083d2b08.png)

Making a docker container for 7tag would be great to quickly try out the app without running into installation problems. Any help to get this to work is appreciated

**Comment by pszostak** [comment]
Hello,
what kind of server do you use?

**Comment by suruchi-shah** [comment]
I am using Symfony to run it locally

**Comment by pszostak** [comment]
To run 7tag, you need to use Apache web server. 
Please check all requirements: https://7tag.org/docs/software-requirements/

We are also working on Docker, so it'll be easier to setup environment.
