### ISSUE TITLE
Restrict access to management interface

### ISSUE THREAD

**Issue by spaiz** [seventag/seventag#574]
Hi.

Say I installed 7tag on our server. Now, every visitor can access the main page of 7tag and to try sign in. Bad users can also to try bruttforsing /api/ pathes directly.

In short, we want to setup  7TAG management interface on an separate server with access from internal office IPs.

Have you an built-in solution to restrict access to to management interface?

p.s.
Can we restrict access from the web to /api/ path? Will 7tag still to do his work correctly?

Thank.

**Comment by michalsikora** [comment]
Hi,
we do not have build-in solution at this moment but you can modify security configuration 
https://github.com/seventag/seventag/blob/develop/app/config/security.yml for specific routes basing on this cookbook: http://symfony.com/doc/current/cookbook/security/access_control.html

Thanks

**Comment by spaiz** [comment]
Thank you. We will look.
