### ISSUE TITLE
The fields with the ability to insert variables value

### ISSUE THREAD

**Issue by ArekZc** [seventag/seventag#80]
As a user i would like to have possibility to set some fields with values from variables, so i could place my identificators and keys in variable and use it everywhere inside container

*Criteria*:
* Fields should be labeled accordingly, so i could easy determine if i could use variable in this field
* Variables should be placed like {{ variableName }} in input field
* Field should have autocomplite so i should have hints which variable i could use

**Comment by marnits** [comment]
Implemented in version 1.3.0
